/*
 *
 * SignupPage constants
 *
 */

export const SIGNUP_GUEST_REQUEST = 'app/SignupPage/SIGNUP_GUEST_REQUEST';
export const SIGNUP_GUEST_SUCCESS = 'app/SignupPage/SIGNUP_GUEST_SUCCESS';
export const SIGNUP_GUEST_ERROR = 'app/SignupPage/SIGNUP_GUEST_ERROR';

export const FACEBOOK_LOGIN_REQUEST = 'app/SignupPage/FACEBOOK_LOGIN_REQUEST';
export const FACEBOOK_LOGIN_SUCCESS = 'app/SignupPage/FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_ERROR = 'app/SignupPage/FACEBOOK_LOGIN_ERROR';

export const GET_SMS_VERIFICATION_REQUEST = 'app/SignupPage/GET_SMS_VERIFICATION_REQUEST';
export const GET_SMS_VERIFICATION_SUCCESS = 'app/SignupPage/GET_SMS_VERIFICATION_SUCCESS';
export const GET_SMS_VERIFICATION_ERROR = 'app/SignupPage/GET_SMS_VERIFICATION_ERROR';

export const CHECK_SMS_VERIFICATION_REQUEST = 'app/SignupPage/CHECK_SMS_VERIFICATION_REQUEST';
export const CHECK_SMS_VERIFICATION_SUCCESS = 'app/SignupPage/CHECK_SMS_VERIFICATION_SUCCESS';
export const CHECK_SMS_VERIFICATION_ERROR = 'app/SignupPage/CHECK_SMS_VERIFICATION_ERROR';
