/*
 *
 * SignupPage constants
 *
 */

export const CHECK_SMS_VERIFICATION_REQUEST =
  'app/SignupPage/CHECK_SMS_VERIFICATION_REQUEST';
export const CHECK_SMS_VERIFICATION_SUCCESS =
  'app/SignupPage/CHECK_SMS_VERIFICATION_SUCCESS';
export const CHECK_SMS_VERIFICATION_ERROR =
  'app/SignupPage/CHECK_SMS_VERIFICATION_ERROR';
