/*
 *
 * Otp constants
 *
 */

export const CHECK_SMS_VERIFICATION_REQUEST =
  'app/Otp/CHECK_SMS_VERIFICATION_REQUEST';
export const CHECK_SMS_VERIFICATION_SUCCESS =
  'app/Otp/CHECK_SMS_VERIFICATION_SUCCESS';
export const CHECK_SMS_VERIFICATION_ERROR =
  'app/Otp/CHECK_SMS_VERIFICATION_ERROR';

export const CHECK_EMAIL_VERIFICATION_REQUEST =
  'app/Otp/CHECK_EMAIL_VERIFICATION_REQUEST';
export const CHECK_EMAIL_VERIFICATION_SUCCESS =
  'app/Otp/CHECK_EMAIL_VERIFICATION_SUCCESS';
export const CHECK_EMAIL_VERIFICATION_ERROR =
  'app/Otp/CHECK_EMAIL_VERIFICATION_ERROR';

export const ADD_CART_ITEMS_REQUEST = 'app/Otp/ADD_CART_ITEMS_REQUEST';
export const ADD_CART_ITEMS_SUCCESS = 'app/Otp/ADD_CART_ITEMS_SUCCESS';
export const ADD_CART_ITEMS_ERROR = 'app/Otp/ADD_CART_ITEMS_ERROR';
