/*
 *
 * Otp constants
 *
 */

export const CHECK_SMS_VERIFICATION_REQUEST =
  'app/Otp/CHECK_SMS_VERIFICATION_REQUEST';
export const CHECK_SMS_VERIFICATION_SUCCESS =
  'app/Otp/CHECK_SMS_VERIFICATION_SUCCESS';
export const CHECK_SMS_VERIFICATION_ERROR =
  'app/Otp/CHECK_SMS_VERIFICATION_ERROR';
