/*
 *
 * FreeDrinkCode constants
 *
 */

export const GENERATE_FREE_DRINK_CODE_REQUEST = 'app/FreeDrinkCode/GENERATE_FREE_DRINK_CODE_REQUEST';
export const GENERATE_FREE_DRINK_CODE_SUCCESS = 'app/FreeDrinkCode/GENERATE_FREE_DRINK_CODE_SUCCESS';
export const GENERATE_FREE_DRINK_CODE_ERROR = 'app/FreeDrinkCode/GENERATE_FREE_DRINK_CODE_ERROR';
