/*
 *
 * SignupPage constants
 *
 */

export const SUBMIT_EVENT_CODE_REQUEST = 'app/SignupPage/SUBMIT_EVENT_CODE_REQUEST';
export const SUBMIT_EVENT_CODE_SUCCESS = 'app/SignupPage/SUBMIT_EVENT_CODE_SUCCESS';
export const SUBMIT_EVENT_CODE_ERROR = 'app/SignupPage/SUBMIT_EVENT_CODE_ERROR';

export const GET_GUEST_EVENTS_REQUEST = 'app/SignupPage/GET_GUEST_EVENTS_REQUEST';
export const GET_GUEST_EVENTS_SUCCESS = 'app/SignupPage/GET_GUEST_EVENTS_SUCCESS';
export const GET_GUEST_EVENTS_ERROR = 'app/SignupPage/GET_GUEST_EVENTS_ERROR';

export const GET_AGENCY_EVENTS_REQUEST = 'app/SignupPage/GET_AGENCY_EVENTS_REQUEST';
export const GET_AGENCY_EVENTS_SUCCESS = 'app/SignupPage/GET_AGENCY_EVENTS_SUCCESS';
export const GET_AGENCY_EVENTS_ERROR = 'app/SignupPage/GET_AGENCY_EVENTS_ERROR';

