/*
 *
 * Otp constants
 *
 */

export const CHECK_SMS_VERIFICATION_REQUEST =
  'app/OtpPage/CHECK_SMS_VERIFICATION_REQUEST';
export const CHECK_SMS_VERIFICATION_SUCCESS =
  'app/OtpPage/CHECK_SMS_VERIFICATION_SUCCESS';
export const CHECK_SMS_VERIFICATION_ERROR =
  'app/OtpPage/CHECK_SMS_VERIFICATION_ERROR';

export const CHECK_EMAIL_VERIFICATION_REQUEST =
  'app/OtpPage/CHECK_EMAIL_VERIFICATION_REQUEST';
export const CHECK_EMAIL_VERIFICATION_SUCCESS =
  'app/OtpPage/CHECK_EMAIL_VERIFICATION_SUCCESS';
export const CHECK_EMAIL_VERIFICATION_ERROR =
  'app/OtpPage/CHECK_EMAIL_VERIFICATION_ERROR';

export const SEND_MOBILE_OTP_REQUEST = 'app/OtpPage/SEND_MOBILE_OTP_REQUEST';
export const SEND_MOBILE_OTP_SUCCESS = 'app/OtpPage/SEND_MOBILE_OTP_SUCCESS';
export const SEND_MOBILE_OTP_ERROR = 'app/OtpPage/SEND_MOBILE_OTP_ERROR';
