/*
 *
 * Otp constants
 *
 */

export const CHECK_SMS_VERIFICATION_REQUEST =
  'app/OtpPage/CHECK_SMS_VERIFICATION_REQUEST';
export const CHECK_SMS_VERIFICATION_SUCCESS =
  'app/OtpPage/CHECK_SMS_VERIFICATION_SUCCESS';
export const CHECK_SMS_VERIFICATION_ERROR =
  'app/OtpPage/CHECK_SMS_VERIFICATION_ERROR';

export const CHECK_EMAIL_VERIFICATION_REQUEST =
  'app/OtpPage/CHECK_EMAIL_VERIFICATION_REQUEST';
export const CHECK_EMAIL_VERIFICATION_SUCCESS =
  'app/OtpPage/CHECK_EMAIL_VERIFICATION_SUCCESS';
export const CHECK_EMAIL_VERIFICATION_ERROR =
  'app/OtpPage/CHECK_EMAIL_VERIFICATION_ERROR';
